# Generated by Django 5.2 on 2025-04-23 19:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2025, 4, 23, 19, 48, 15, 241434, tzinfo=datetime.timezone.utc)),
        ),
    ]
