# Generated by Django 5.2 on 2025-04-23 19:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_alter_chat_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='created_at',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2025, 4, 23, 19, 50, 1, 699484, tzinfo=datetime.timezone.utc)),
        ),
    ]
